# Generated by Django 6.0.6 on 2026-07-11 14:13

import django.db.models.deletion
import django.db.models.manager
import produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, default=None, null=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('dias_atencao', models.PositiveIntegerField(default=30, help_text="A partir de quantos dias antes do vencimento o lote entra em nível 'Atenção'.")),
                ('dias_critico', models.PositiveIntegerField(default=7, help_text="A partir de quantos dias antes do vencimento o lote entra em nível 'Crítico'.")),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'ordering': ['nome'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, default=None, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('preco_venda', models.FloatField(help_text='Valor em R$ pelo qual o produto é vendido.')),
                ('categoria', models.ForeignKey(default=produtos.models.get_categoria_padrao, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'ordering': ['nome'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, default=None, null=True)),
                ('nome_lote', models.CharField(blank=True, editable=False, max_length=40, unique=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('custo_unitario_compra', models.FloatField(help_text='Custo unitário de aquisição. Usado também para calcular o prejuízo de lotes vencidos.')),
                ('nivel_vencimento', models.IntegerField(blank=True, choices=[(0, 'OK'), (1, 'Atenção'), (2, 'Crítico'), (3, 'Vencido')], null=True)),
                ('esgotado', models.BooleanField(default=False, help_text='Lote sem estoque. Lotes esgotados não têm o nível de vencimento recalculado.')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateTimeField(blank=True, null=True)),
                ('tempo_vencimento', models.PositiveIntegerField(blank=True, help_text='Dias até o vencimento, para lotes sem data fixa.', null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
                'ordering': ['data_validade'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'SKU / Código de barras',
                'verbose_name_plural': 'SKUs / Códigos de barra',
                'db_table': 'produto_skus',
            },
        ),
        migrations.CreateModel(
            name='ContadorLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('sequencial', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'db_table': 'contadores_lote',
                'unique_together': {('produto', 'data')},
            },
        ),
    ]
