# Generated by Django 6.0.6 on 2026-07-08 14:28

from django.db import migrations

def criar_categoria_padrao(apps, schema_editor):
    # Recupera o model dinamicamente para evitar problemas de importação
    Categoria = apps.get_model('produtos', 'Categoria')
    Categoria.objects.get_or_create(nome="Sem Categoria")

class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_categoria_padrao),
    ]
