# Generated by Django 6.0.7 on 2026-08-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20260708_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.FloatField(help_text='Percentual de desconto sugerido (0 a 100).')),
                ('dias_para_vencimento', models.PositiveIntegerField(help_text='A regra passa a valer quando faltar esse número de dias (ou menos) para o vencimento.')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_desconto', to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Regra de desconto',
                'verbose_name_plural': 'Regras de desconto',
                'db_table': 'regras_desconto',
                'ordering': ['categoria__nome', '-percentual'],
                'unique_together': {('categoria', 'percentual', 'dias_para_vencimento')},
            },
        ),
    ]
