# Generated by Django 6.0.7 on 2026-10-09 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_regradesconto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('quantidade', models.PositiveIntegerField(help_text='Unidades movimentadas; em ajustes, saldo final desejado.')),
                ('quantidade_antes', models.PositiveIntegerField()),
                ('quantidade_depois', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='produtos.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimentos_estoque',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
